export const SET_TOTAL_SCORE = "SET_TOTAL_SCORE";
export const RESET_TOTAL_SCORE = "RESET_TOTAL_SCORE";
export const ADD_ASSESSMENT_DATA = "ADD_ASSESSMENT_DATA";
export const ACTIVATE_ASSESSMENT_LOADING = "ACTIVATE_ASSESSMENT_LOADING";
export const SET_ADMIN_TOKEN = "SET_ADMIN_TOKEN";
export const RESET_ADMIN_TOKEN = "RESET_ADMIN_TOKEN";