export const LOGIN_ROUTE = "/login"
export const REGISTER_ROUTE = "/register"
export const FORGOT_PASSWORD_ROUTE = "/forgot-password"
export const RESET_PASSWORD_ROUTE = "/reset-password"
export const ASSESSMENT_ROUTE = "/"
export const ADMIN_LOGIN_ROUTE = "/admin/login"
export const ADMIN_HOME_ROUTE = "/admin"
export const ADMIN_ASSESSMENT_DATA_ROUTE = "/admin/assessment-data"